language: rust

rust:
  - 1.44.0-nightly

matrix:
  include:
    - os: linux
      dist: xenial

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  
cache:
  directories:
    - .cache
