services:
  - docker

before_install:
  - docker pull rust:1.44.0

before_script:
  - sudo apt install ruby-coveralls

script:
  - docker run -it -v $PWD:/teaclave -w /teaclave rust:1.44.0 /bin/sh -c "cargo build; cargo test"

after_success:
  - coveralls

cache:
  directories:
    - .cache
