services:
  - docker

before_install:
  - docker pull rust:1.44.0

before_script:
  - sudo apt update

script:
  - docker run -it -v $PWD:/teaclave -w /teaclave rust:1.44.0 /bin/sh -c "cargo test"

after_success:
  - bash -c "bash <(curl -s https://codecov.io/bash) -f ./cov.info"

cache:
  directories:
    - .cache
