language: rust

rust:
  - nightly

matrix:
  include:
    - os: linux
      dist: xenial

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - .cache
