sudo: true

services:
  - docker

before_install:
  - docker pull rust:1.44.0

before_script:
  - apt update
  - apt install coveralls
  - apt install npm

script:
  - npm run coveralls
  - docker run -it -v $PWD:/teaclave -w /teaclave rust:1.44.0 /bin/sh -c "cargo test"

after_success:
#  - bash -c "bash <(curl -s https://codecov.io/bash) -f ./cov.info"
  - cat ./cov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - .cache
