services:
  - docker

before_install:
  - docker pull rust:1.44.0

before_script:
  - sudo apt update
  - sudo apt install ruby-coveralls

script:
  - docker run -it --name travis -v $PWD:/teaclave -w /teaclave rust:1.44.0 /bin/sh -c "cargo build; cargo test"

after_success:
  - docker cp travis:/teaclave/.coverage ./
  - sed -i "s@\"/test-travis/@\"${PWD}/@g" .coverage
  - coveralls

cache:
  directories:
    - .cache
